[project]
name = "quick-send"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-language>=2.18.0",
    "google-generativeai>=0.8.5",
    "requests>=2.32.5",
]
